stevespringett/Alpine

- alpine/src/main/java/alpine/tasks/LdapSyncTask.java
The basedn setting has a mistake. 
The value if basedn is set to server_url.
When dependency-track sync the user from ldap, the task will fail.
the ldap log（the base is empty）:
```
mail slapd[12103]: conn=35081 op=0 RESULT tag=97 err=0 text=
mail slapd[12103]: conn=35081 op=1 SRCH base="" scope=2 deref=3 filter="(?userPrincipalName=add)"
mail slapd[12103]: conn=35081 op=1 SRCH attr=1.1
mail slapd[12103]: conn=35081 op=1 SEARCH RESULT tag=101 err=32 nentries=0 text=
```
the dependency-track log:
```
569 [] INFO [alpine.tasks.LdapSyncTask] Starting LDAP synchronization task
583 [] ERROR [alpine.tasks.LdapSyncTask] Error occurred during LDAP synchronization
583 [] ERROR [alpine.tasks.LdapSyncTask] [LDAP: error code 32 - No Such Object]
583 [] INFO [alpine.tasks.LdapSyncTask] LDAP …
```
> fix the basedn in LdapSyncTask

- alpine/src/main/java/alpine/Config.java
- alpine/src/main/java/alpine/auth/LdapAuthenticationService.java
Added an optional LDAP configuration improvement needed for some type of servers.
Specifies how to map the username identifier entered by the user to that passed through to LDAP.
If is configured to a non-empty value, the substring %s in this value will be replaced with the entered username.
The recommended format of this value depends on your LDAP server(Active Directory, OpenLDAP, etc.).
Examples:
alpine.ldap.auth.username.format=%s
alpine.ldap.auth.username.format=%s@example.com
alpine.ldap.auth.username.format=uid=%s,ou=People,dc=example,dc=com
alpine.ldap.auth.username.format=userPrincipalName=%s,ou=People,dc=example,dc=com
> Specifies how to map the user identifier entered by the user to that passed through to LDAP

- alpine/src/main/java/alpine/auth/Authenticator.java
Return FORCE_PASSWORD_CHANGE and SUSPENDED exceptions for ManagedUsers when LDAP authentication is enabled.
> Fixes #16 - Throw exceptions for valid ManagedUsers

- alpine/src/main/java/alpine/auth/LdapConnectionWrapper.java
In the process of integrating dependency-track with MS Active Directory, I found that it fails to get groups for a ldap user if DN's CN has special characters, e.g., `CN=firstName\, familyName`
The potential fix is to escape the **user_groups_filter** after substitution. With this fix, I am able to get groups for a ldap user with special CN.
> It fails to get groups for a ldap user if CN has special characters

- alpine/src/main/java/alpine/Config.java
- alpine/src/main/java/alpine/auth/LdapConnectionWrapper.java
- alpine/src/main/java/alpine/persistence/JdoProperties.java
- example/src/main/resources/application.properties
I propose a simple update to read password from files. I need this to be able to read password from files  created with docker secrets. If you accept this a similar change would be needed in the DT repo as well, to handle HTTP_PROXY_PASSWORD_FILE.
> Read password property from file

- alpine/src/main/java/alpine/auth/OidcConfigurationResolver.java
- alpine/src/test/java/alpine/auth/OidcConfigurationResolverTest.java
This PR addresses an issue where Alpine's `OidcConfigurationResolver` would attempt to resolve an OpenID Connect configuration, even though `alpine.oidc.enabled` was `false`.
> Don't attempt to resolve OIDC config when OIDC is disabled

- alpine/src/main/java/alpine/validation/RegexSequence.java
Required to match URI that contain authentication information (http://user@example.com) or in the case of packageurl the version (pkg:maven/us.springett/alpine@1.8.0-SNAPSHOT).
> Allow @ characters in HTTP_URI regex sequence

- alpine/src/main/java/alpine/auth/OidcAuthenticationService.java
- alpine/src/main/java/alpine/auth/OidcUserInfo.java
- alpine/src/test/java/alpine/auth/OidcUserInfoTest.java
Fixes an issue where users couldn't use "email" as username claim, see https://owasp.slack.com/archives/C6R3R32H4/p1616153299039200
The configured claim [would be accessed via `OidcUserInfo#getClaim`](https://github.com/stevespringett/Alpine/blob/alpine-parent-1.9.1/alpine/src/main/java/alpine/auth/OidcAuthenticationService.java#L68), which in turn was populated with `@JsonAnySetter`. Because `email` was already annotated with `@JsonProperty`, it wouldn't be passed to the any setter and thus wasn't accessible via `#getClaim`, see https://fasterxml.github.io/jackson-annotations/javadoc/2.9/com/fasterxml/jackson/annotation/JsonAnySetter.html.
> Use a more generic approach for parsing OIDC UserInfo responses

- alpine/src/main/java/alpine/model/ApiKey.java
- alpine/src/test/java/alpine/model/ApiKeyTest.java
Now for example in Dependency Track logs I see:
```
15:57:17.662 INFO [ProjectResource] Project pkg:npm/internal-app/domains-advanced-dns-application@deploy-production updated by z3KFI9e5d[EDITED]ChhF2
15:57:18.362 INFO [BomUploadProcessingTask] Processing CycloneDX BOM uploaded to project: 086f785e-4478-4ac9-886d-349d7281a71b
15:57:18.420 INFO [ProjectResource] Project pkg:npm/internal-app/domains-advanced-dns-application@deploy-production updated by z3KFI9e5d[EDITED]ChhF2
15:57:19.078 INFO [ProjectResource] Project pkg:npm/%40nodejsTools/eslint-config@3.4.1 updated by z3KFI9e5d[EDITED]ChhF2
```
> fix: fixed security issue which cause leakage of API keys to logs

- alpine/src/main/java/alpine/auth/LdapConnectionWrapper.java
- example/src/main/resources/application.properties
In our company, we use Dependency-Track which connects to our internal OpenLDAP. The problem is, that Dependency-Track doesn’t synchronise groups with teams. After triple-checking our configuration, I discovered that the filter for synchronising groups uses `memberUid={USER_DN}`. In our LDAP, however, `memberUid`s in groups are `uid`s, which are the same as usernames. It turns out that the only template that will be substituted in this filter is `{USER_DN}`.
W specifically need a template for usernames so I didn’t think adding a column for `uid` is wise, given that one for username already exists. That’s why I didn’t change `LdapUser`.
> add USERNAME template in LDAP wrapper

- .github/workflows/maven.yml
- .gitignore
- alpine-common/src/main/java/alpine/common/util/ByteFormat.java
- pom.xml
Surprisingly few changes necessary for this upgrade. Beside DataNucleus, all other libraries are already Java 17 compatible, including Jersey. Adoption in DT is equally unproblematic.
Closes #383
> Raise baseline Java version to 17

- pom.xml
Also update datanucleus-api-jdo to 6.0.1, there is no 6.0.2 version for it yet.
This will resolve a blocker we have for DT 4.6, caused by datanucleus-rdbms <= 6.0.1 not working with MSSQL: https://github.com/DependencyTrack/dependency-track/issues/1930
> Update datanucleus-core and datanucleus-rdbms to 6.0.2

- alpine-common/src/main/java/alpine/Config.java
- alpine-server/src/main/java/alpine/server/servlets/MetricsServlet.java
- alpine-server/src/test/java/alpine/server/servlets/MetricsServletTest.java
The metrics endpoint is intended to be used by machines, and access has to be available as soon as the application starts. While it's not viable to integrate this endpoint with Alpine's default AuthN/AuthZ model, basic auth is a good compromise.
Also, Prometheus supports basic auth, but not custom headers like `X-Api-Key` or similar.
Signed-off-by: nscuro <nscuro@protonmail.com>
> Add support for protecting metrics with basic authentication

- alpine-infra/src/main/java/alpine/persistence/JdoProperties.java
- alpine-server/src/main/java/alpine/server/persistence/PersistenceManagerFactory.java
This PR adds metrics support for both DataNucleus and HikariCP, providing insights into how the persistence layer of Alpine is doing.
While DataNucleus provides a more high-level view of things, the HikariCP metrics will hopefully allow users to better tune their pool size. 
Note: The DataNucleus statistics are not thread safe until datanucleus-core 6.0.2 (see https://github.com/datanucleus/datanucleus-core/pull/478) and may yield weird numbers as a consequence. They'll start to emit reliable numbers as soon as we update to 6.0.2.
Here's an example of how this may look in a Grafana dashboard:
> Add support for persistence metrics

- alpine-common/src/main/java/alpine/Config.java
- alpine-infra/src/main/java/alpine/security/crypto/KeyManager.java
- alpine-infra/src/test/java/alpine/security/crypto/KeyManagerTest.java
- example/src/main/resources/application.properties
Using OS makes it impractical to provide a key that was generated before Alpine / the application using Alpine was first launched.
Secret keys can be loaded both in the old and the new format. This is done for backwards compatibility. Existing deployments of Alpine-based apps will not have to do anything and continue to function as before.
New keys will only be generated in the new encoded format. There is no automatic conversion of existing keys happening, because some users of Alpine may already have the key file set to read-only.
Additionally, the location of the secret key is now configurable. This is important to have when using k8s secrets, as nested mounts (e.g. `-v "./data:/data" -v "./secret.key:/data/.alpine/keys/secret.key"`) are an anti-pattern.
Closes #436
> Save and load secret key using encoded bytes format instead of Object Serialization

- alpine-model/src/main/java/alpine/model/LdapUser.java
- alpine-server/src/main/java/alpine/server/auth/LdapConnectionWrapper.java
See https://github.com/DependencyTrack/dependency-track/issues/2320#issuecomment-1361666943 and https://github.com/DependencyTrack/dependency-track/pull/2371#issuecomment-1385649780 for reference.
Currently, no email addresses are fetched from the LDAP server for LDAP users. And even if they were correctly fetched, it would always be required to sync the email addresses from the server before using them, resulting in an unnecessary overhead.
This can be avoided by persisting the email address of a LDAP user every time it is synced from the LDAP server.
With this PR, the attributes of a LDAP user are now all fetched from the LDAP server and the fetched email attribute of the LDAP user is now being persisted for future use in other contexts.
> Fix user email attribute not being persisted and fetched from LDAP server

- alpine-common/pom.xml
- alpine-common/src/main/java/alpine/common/util/ProxyConfig.java
- alpine-common/src/main/java/alpine/common/util/ProxyUtil.java
- alpine-common/src/test/java/alpine/common/util/ProxyConfigTest.java
- alpine-common/src/test/java/alpine/common/util/ProxyUtilTest.java
- alpine-common/src/test/resources/alpine.version
As usage of proxies can be necessary for Alpine-internal functionality too, and proxy behavior should behave consistently, moving this logic to Alpine is necessary.
Signed-off-by: nscuro <nscuro@protonmail.com>
> Port proxy util methods from Dependency-Track

- alpine-server/src/main/java/alpine/server/persistence/PersistenceManagerFactory.java
This PR exposes a few additional metrics for the caches provided by DataNucleus.
Using these metrics, it's now possible to monitor the number of entries in the following caches:
* [Second Level](https://www.datanucleus.org/products/accessplatform_6_0/jdo/persistence.html#cache_level2)
* [Generic Query Compilation](https://www.datanucleus.org/products/accessplatform_6_0/jdo/query.html#cache_genericcompilation)
* [Datastore Query Compilation](https://www.datanucleus.org/products/accessplatform_6_0/jdo/query.html#cache_datastorecompilation)
* [Query Results](https://www.datanucleus.org/products/accessplatform_6_0/jdo/query.html#cache_results)
Except the query results cache, all caches are enabled per default in DataNucleus.
> Add metrics for DataNucleus caches

- pom.xml
logback 1.4.x targets Jakarta APIs (`jakarta.*`), while 1.3.x targets Java EE APIs (`javax.*`).
Both 1.4.x and 1.3.x require SLF4J 2.0.x: https://logback.qos.ch/news.html
With the current `master` of Alpine, the logging in Dependency-Track no longer works.
I tried downgrading logback to 1.3.5, and updating SLF4J to 2.0.6, but that causes build errors during DataNucleus enhancement:
```
[ERROR] Failed to execute goal org.datanucleus:datanucleus-maven-plugin:6.0.0-release:enhance (default) on project dependency-track: Execution default of goal org.datanucleus:datanucleus-maven-plugin:6.0.0-release:enhance failed: An API incompatibility was encountered while executing org.datanucleus:datanucleus-maven-plugin:6.0.0-release:enhance: java.lang.ExceptionInInitializerError: null
[ERROR] …
```
> Revert logback update

- alpine-server/src/main/java/alpine/server/auth/OidcConfigurationResolver.java
- alpine-server/src/main/java/alpine/server/auth/OidcUserInfoAuthenticator.java
Hi,
following this (closed/not merged) issue https://github.com/stevespringett/Alpine/pull/422 , I create this new one to make use of the newly created ProxyConfig class in order to have OIDC configuration use proxy if declared in configuration.
Thanks @nscuro for the work on ProxyConfig, looks good to me !
> Use new class ProxyConfig for proxy selection in OIDC configuration

- alpine-infra/src/main/java/alpine/persistence/AlpineQueryManager.java
- alpine-model/src/main/java/alpine/model/OidcUser.java
- alpine-server/src/main/java/alpine/server/auth/OidcAuthenticationService.java
- alpine-server/src/test/java/alpine/server/auth/OidcAuthenticationServiceTest.java
This PR adjusts the OIDC implementation to persist the email address of users, similar to how https://github.com/stevespringett/Alpine/pull/450 did it for LDAP.
There was no particular reason for not persisting the email back when I implemented OIDC, other than "the LDAP implementation does not do it, too". 
In the DT community we're seeing that the email not being persistent is counter-intuitive and prevents certain use cases, see https://github.com/DependencyTrack/dependency-track/issues/2647
> Persist email of OIDC users

- alpine-common/pom.xml
- alpine-common/src/main/java/alpine/Config.java
- alpine-common/src/test/java/alpine/ConfigTest.java
- alpine-common/src/test/resources/Config_testGetPassThroughProperties.properties
- alpine-server/src/main/java/alpine/server/persistence/PersistenceManagerFactory.java
This change is mostly meant to address #493, but may be useful for other use cases as well.
Due to the sheer amount of configuration options in DataNucleus (and potentially other frameworks), it is not practical to add `AlpineKey`s for all of them.
With this change, it is possible to disable the DataNucleus L2 cache by either:
* Setting the property `alpine.datanucleus.cache.level2.type=none` in `application.properties`, or
* Setting the environment variable `ALPINE_DATANUCLEUS_CACHE_LEVEL2_TYPE=none`
Closes #493
> Allow customization of DataNucleus via pass-through properties

- alpine-common/src/main/java/alpine/common/metrics/MeterRegistryCustomizer.java
- alpine-common/src/main/java/alpine/common/metrics/Metrics.java
- alpine-common/src/test/java/alpine/common/metrics/MetricsTest.java
- alpine-common/src/test/resources/META-INF/services/alpine.common.metrics.MeterRegistryCustomizer
Because it is crucial that filters are registered *before* the individual meters, `ServiceLoader` is used to load and apply all customizations immediately after the registry is created.
Closes #500
> Add ability to customize the Micrometer `MeterRegistry`

- .github/dependabot.yml
- alpine-server/pom.xml
- pom.xml
This makes `logstash-logback-encoder` (and its required dependencies) available in the executable WAR's classpath, which enables usage of `LogstashEncoder` in the logback configuration file.
A minimal sample `logback.xml` using the encoder looks like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration scan="true">
<appender name="JSON_STDOUT" class="ch.qos.logback.core.ConsoleAppender">
<encoder class="net.logstash.logback.encoder.LogstashEncoder" />
</appender>
<root level="INFO">
<appender-ref ref="JSON_STDOUT" />
</root>
</configuration>
```
Closes #502
> Add support for logging in JSON format

- alpine-common/src/main/java/alpine/common/util/ExecutorUtil.java
- alpine-infra/src/main/java/alpine/event/framework/BaseEventService.java
- alpine-infra/src/main/java/alpine/event/framework/EventService.java
- alpine-infra/src/main/java/alpine/event/framework/IEventService.java
- alpine-infra/src/main/java/alpine/event/framework/SingleThreadedEventService.java
- alpine-infra/src/main/java/alpine/notification/INotificationService.java
- alpine-infra/src/main/java/alpine/notification/NotificationService.java
Using solely `IEventService#shutdown` and `NotificationService#shutdown` will cause queued events and notifications to be lost. This is problematic when event and notification processing must be relied upon.
It is now possible to provide a timeout to the `shutdown` method. Alpine will wait for `ExecutorService` queues to be drained until the timeout is exceeded. A status message about remaining queued items, and active thread counts is logged every 5sec during shutdown.
Ideally, the order of subsystems being shut down would be:
* Web app / REST API; Stopping new events from being emitted via user interactions
* Eventing; Processing all events enqueued prior to Web app / REST API shutdown
* Notifications; Processing all notifications emitted during event processing
While this is not a …
> Allow for drainage of `EventService` and `NotificationService` on shutdown

- alpine-common/src/main/java/alpine/Config.java
- alpine-infra/src/main/java/alpine/security/crypto/KeyManager.java
- example/src/main/resources/application.properties
Similarly to what was done for the secret key in #437, this allows pre-generated keys mounted into the application's container to be used.
This is necessary to support deployments where multiple app instances must share the same keys.
> Allow paths of public/private key pair to be customized

- alpine-common/src/main/java/alpine/Config.java
- alpine-infra/src/main/java/alpine/security/ApiKeyGenerator.java
- alpine-infra/src/test/java/alpine/security/ApiKeyGeneratorTest.java
- alpine-model/src/main/java/alpine/model/ApiKey.java
- alpine-model/src/test/java/alpine/model/ApiKeyTest.java
- alpine-server/src/main/java/alpine/server/filters/AuthorizationFilter.java
- example/src/main/resources/application.properties
This adds support for API key prefixes to assist secret scanning. The default API key prefix is "dta_" and may be changed with the alpine.secret.api.keyprefix property.
See https://github.com/DependencyTrack/dependency-track/issues/2543
This does not invalidate old API keys that do not use the new format. The user is free to entirely disable the prefix by setting the property to an empty string.
> Add API key prefix support

- pom.xml
Jersey 2.40 includes support for Java 21: https://projects.eclipse.org/projects/ee4j.jersey/releases/2.40
> Bump Jersey from `2.38` to `2.40`

- pom.xml
Version 7.4 requires logback v2 which Alpine currently does not support.
Using the JSON encoder with v7.4 currently fails, see https://github.com/DependencyTrack/dependency-track/issues/3127
> Revert `logstash-logback-encoder` to 7.3

- pom.xml
Changelog: https://www.eclemma.org/jacoco/trunk/doc/changes.html
> Bump JaCoCo to `0.8.11` for Java 21 support

- alpine-executable-war/pom.xml
The Jetty update resolves CVE-2023-40167 and GHSA-58qw-p7qm-5rvh.
> Bump embedded Jetty to `10.0.18` and remove unused `jetty-webapp-logging` dependency

- alpine-infra/src/main/java/alpine/event/framework/BaseEventService.java
If an unhandled exception occurred, the event would previously not be removed from the `chainTracker` map.
This can be problematic for events marked as singleton, as consecutive dispatches of the same event would be ignored, as the previously failed event was never removed from the tracking map.
> Ensure `ChainableEvent`s are being removed from tracked events

- alpine-common/src/main/java/alpine/common/util/PathUtil.java
`PathUtil#resolve` was previously checking for the occurrence of `"~" + File.separator` to determine whether `~` shall be expanded to the user's home directory.
`File.separator` is `/` on UNIX and `\` on Windows. The default of `alpine.data.directory` is `~/.alpine`, causing the aforementioned check to always fail on Windows.
> Fix path resolution of `~` on Windows

- alpine-common/src/main/java/alpine/Config.java
- alpine-server/src/main/java/alpine/server/persistence/PersistenceManagerFactory.java
- example/src/main/resources/application.properties
When using external schema management solutions like Flyway or Liquibase, having DataNucleus / Alpine perform schema modifications automatically can cause undesired side effects.
The new property `alpine.database.migration.enabled` defaults to `true` to preserve existing behavior.
> Add ability to disable automatic schema management and migrations

- alpine-infra/src/main/java/alpine/persistence/AlpineQueryManager.java
- alpine-model/src/main/java/alpine/model/ApiKey.java
- alpine-server/src/main/java/alpine/server/filters/ApiKeyUsageTracker.java
- alpine-server/src/main/java/alpine/server/filters/AuthenticationFilter.java
In order to avoid introducing additional latency to requests, API key usage is buffered in-memory and asynchronously flushed to the database in intervals of 30s.
An API key counts as "used" if authentication with it succeeds.
Also, add support for an optional comment for API keys, as requested in #536.
Closes #362
Closes #430
Closes #536
> Track API key creation and last usage

- alpine-common/src/main/java/alpine/Config.java
- alpine-infra/src/main/java/alpine/persistence/AlpineQueryManager.java
- alpine-server/src/main/java/alpine/server/auth/OidcAuthenticationService.java
- alpine-server/src/test/java/alpine/server/auth/OidcAuthenticationServiceTest.java
The assignment of (a) default team(s) happens once during user provisioning, to give administrators a chance to change the teams for a user later.
The assignment of (a) default team(s) does not go through the indirection of an OIDC Group, and expects the administrator to directly specify the teams the user should be a member of by default. This is intentional, because otherwise it could be confusing what would happen when the mapping between OIDC Groups and Teams changes after a user was already provisioned. This also matches the UI, which primarily shows (and allows changes to) the 'Team membership' of a user on the 'OpenID Connect Users' page, rather than showing the OIDC Group membership.
Implements https://github.com/stevespringett/Alpine/issues/411
> oidc: default team

- .github/dependabot.yml
- pom.xml
logback 1.2.x is no longer receiving updates, and logback 1.3.x upwards depends on SLF4J 2.x.
The DataNucleus plugin fails when SLF4J 1.x is no longer present. Hence, SLF4J 1.x was added as a dependency specifically for the plugin.
Tested with Dependency-Track 4.11.0-SNAPSHOT. Both standard format and JSON format continue to work with this change.
> Bump `logback` to 1.3.14 and `slf4j-api` to 2.0.12

- alpine-server/src/main/java/alpine/server/persistence/PersistenceManagerFactory.java
As reported via https://github.com/DependencyTrack/dependency-track/discussions/1987?notification_referrer_id=NT_kwDOAFbe1bI0NTA0OTczODEyOjU2OTMxNDE&notifications_query=repo%3ADependencyTrack%2Fdependency-track#discussioncomment-9276378
This appears to be a regression introduced via #439.
> Fix `ALPINE_DATABASE_PASSWORD_FILE` not being considered

- alpine-infra/src/main/java/alpine/persistence/AbstractAlpineQueryManager.java
- alpine-infra/src/main/java/alpine/persistence/NotSortableException.java
Only persistent fields can be queried and sorted by. Trying to sort by a non-persistent field will cause an exception to be thrown in the persistence layer.
To users it is not immediately obvious which field is persistent, and which is computed. It would be good to provide a helpful error message as to what went wrong when a sorting request can not be fulfilled.
Instead of checking the candidate classes' fields directly, leverage the type metadata of DataNucleus to figure out which field is persistent.
Use specific exception messages for whether a field is not persistent, or doesn't exist at all.
Applications built on Alpine can then define a custom `ExceptionMapper` to transform the new `NotSortableException` into an API-friendly format if desired. Alternatively, it can be handled with …
> Check persistence metadata when sorting

- alpine-server/src/main/java/alpine/server/filters/RequestIdFilter.java
- alpine-server/src/test/java/alpine/server/filters/RequestIdFilterTest.java
This adds a new filter that accepts a `X-Request-Id` header (or alternatively generates a random UUID) for each request, and adds it to SLF4J's `MDC`. Being part of the `MDC` allows it to be included in application and audit logs.
The request ID is also included in every response, in the form of an `X-Request-ID` header.
This behavior allows for easier correlation of operations in the system. Accepting provided request IDs enables correlation even across system boundaries.
Many API gateways, service meshes, and reverse proxies transparently set the `X-Request-Id` header. Among them Enovy (https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-request-id), Apache APISIX (https://apisix.apache.org/docs/apisix/next/plugins/request-id/), and Heroku …
> Add filter to track request ID

- alpine-infra/pom.xml
- alpine-infra/src/main/java/alpine/persistence/AbstractAlpineQueryManager.java
- alpine-infra/src/main/java/alpine/persistence/AlpineQueryManager.java
- alpine-infra/src/main/java/alpine/persistence/JdoProperties.java
- alpine-infra/src/main/java/alpine/persistence/ScopedCustomization.java
- alpine-infra/src/main/java/alpine/persistence/Transaction.java
- alpine-infra/src/test/java/alpine/persistence/ScopedCustomizationTest.java
- alpine-infra/src/test/java/alpine/persistence/TransactionTest.java
- alpine-server/src/main/java/alpine/server/persistence/PersistenceManagerFactory.java
The way transactions were previously handled made it impossible to compose multiple transactional operations into larger tasks. `PersistenceManager#currentTransaction()#begin()` fails when the transaction is already active. This in turn opens the door to data inconsistencies, when parts of a task are committed but later operations fail, with no way to roll back to the original state before the task was started.
It also encouraged commits in high frequencies, which can take a toll on the database's write-ahead-log for high volume processing use-cases.
There was no handling of rollbacks, such that a failed commit could have "poisoned" an entire `PersistenceManager`, as no further persistence operations can be performed until after a rollback was executed.
This change introduces the …
> Use lambdas for transaction scoping; Don't reload objects after commit

- alpine-infra/src/main/java/alpine/persistence/AbstractAlpineQueryManager.java
The `getCount` methods were refactored to not modify the original `Query` object in #552. Neither JDO nor DataNucleus offer a mechanism to copy a `Query` object 1:1, hence a new object was created instead.
This however broke `getCount` for queries that make use of subqueries (and potentially other advanced features).
This change reverts it back to temporarily modify the query object again.
> Fix `getCount` for queries with subqueries

- alpine-common/src/main/java/alpine/common/AboutProvider.java
- alpine-model/src/main/java/alpine/model/About.java
- alpine-model/src/test/java/alpine/model/AboutTest.java
- alpine-model/src/test/resources/META-INF/services/alpine.common.AboutProvider
- alpine-server/src/main/java/alpine/server/persistence/DatabaseAboutProvider.java
- alpine-server/src/main/resources/META-INF/services/alpine.common.AboutProvider
Introduces an SPI that applications can use to provide additional data to be exposed via `/api/version`.
Adds an extension for database information.
This came from a requirement in Dependency-Track, where users want insight into what database they're running on: https://github.com/DependencyTrack/dependency-track/issues/2093
Example response of `/api/version` for Dependency-Track:
```json
{
"version": "4.12.0-SNAPSHOT",
"timestamp": "2024-05-14T18:33:19Z",
"framework": {
"version": "2.2.6-SNAPSHOT",
"timestamp": "2024-05-14T18:32:59Z",
"name": "Alpine",
"uuid": "d7a6b868-13a3-4bbd-909d-a7780a9a6b8f"
},
"application": "Dependency-Track",
"systemUuid": "21e013b8-8a51-4314-ac38-bed8cdde21c9",
"uuid": "d1bf53e9-3a1a-4cd5-b65d-e969b51e9840",
"database": {
"productVersion": "2.2.224 …
```
> Make `About` extensible and add extension for database info

- README.md
- alpine-server/pom.xml
- alpine-server/src/main/java/alpine/server/AlpineServlet.java
- alpine-server/src/main/java/alpine/server/filters/AuthenticationFilter.java
- alpine-server/src/main/java/alpine/server/resources/VersionResource.java
- example/src/main/webapp/WEB-INF/web.xml
- example/src/main/webapp/index.html
- example/src/main/webapp/js/example.js
- pom.xml
Removes the Swagger integration in Alpine.
* The Swagger / OpenAPI spec is no longer exposed by default
* Applications wishing to expose their OpenAPI spec can do so on their own, see https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Integration-and-Configuration#exposing-openapi-definition
* Resources provided by Alpine now use `swagger-annotations` in version `2.x`
Closes #1
---
@stevespringett This is in line with my proposal in https://github.com/stevespringett/Alpine/issues/402#issuecomment-1593407468.
I took another mid-term solution regarding the OpenAPI v3 migration though:
* I've [migrated the Dependency-Track code base](https://github.com/DependencyTrack/dependency-track/pull/3726) to Swagger Core 2.x
* Dependency-Track now takes care of exposing the OpenAPI spec on …
> Remove Swagger integration

- alpine-common/src/main/java/alpine/Config.java
- alpine-server/src/main/java/alpine/server/auth/JsonWebToken.java
Fix #534
Should be add to dependency-track doc after the merge
> feat: add alpine.auth.jwt.ttl.seconds config

- alpine-infra/src/main/java/alpine/persistence/AbstractAlpineQueryManager.java
- alpine-infra/src/main/java/alpine/persistence/NotSortableException.java
- alpine-infra/src/main/java/alpine/persistence/Transaction.java
- alpine-infra/src/test/java/alpine/persistence/TransactionTest.java
* Fixes incorrect type parameter for `executeAndCloseResultList`
* The result class is not necessarily equal to the candidate class of the query. Hence, using a wildcard `?` for the `Query` parameter is more fitting.
* Makes `NotSortableException` constructor public
* So it can be used by custom query code of Alpine applications as well.
* Avoid unnecessary exception wrapping in `callInTransaction`.
* Ensure transaction cleanups are always execute.
> Fix incorrect type parameter for `executeAndCloseResultList` and make `NotSortableException` constructor public

- alpine-model/src/main/java/alpine/model/Team.java
Resolves #638 by increasing column length of Team.java `name` field to 255.
> fix: increase name column length to 255

- alpine-common/src/main/java/alpine/Config.java
Alpine currently tries to create the `system.id` file despite the data directory potentially not existing, which causes `NoSuchFileException`s.
> Ensure the data directory exists, and is read- and writable

- alpine-common/src/main/java/alpine/Config.java
Fix an error in https://github.com/stevespringett/Alpine/pull/539
Default value `7 * 24 * 60` seconds is not 7 days.
> fix: default jwt ttl

- alpine-server/src/main/java/alpine/server/auth/AllowApiKeyInQueryParameter.java
- alpine-server/src/main/java/alpine/server/auth/ApiKeyAuthenticationService.java
- alpine-server/src/main/java/alpine/server/auth/AuthenticationWithUriQuery.java
- alpine-server/src/main/java/alpine/server/filters/AuthenticationFilter.java
Introduce new annotation for resources that makes the authentication filter look at the URI query for a parameter containing the API key instead of a header.
This enables clients that cannot supply headers to use authentication- locked resources.
#641
> Allow authentication via URI query parameter

- alpine-infra/src/main/java/alpine/persistence/JdoProperties.java
Any properties modified via pass-through properties should reflect in unit tests.
> Apply DataNucleus pass-through properties in unit test configuration

- alpine-executable-war/src/main/java/alpine/embedded/EmbeddedJettyServer.java
- pom.xml
Standalone Jetty installations provide a means to configure the context via XML files: https://jetty.org/docs/jetty/12/operations-guide/xml/index.html
The mechanism doesn't work for embedded use - XML files need to be discovered and loaded explicitly. For our purposes, applications can place a `jetty-context.xml` file in their `WEB-INF` directory in order for Alpine to discover them.
Since Alpine applications do not directly depend on `alpine-executable-war`, and thus do usually not have access to Jetty classes, the Jetty-native XML configuration was preferred over programmatic customization.
Example `jetty-context.xml` that disabled classpath scanning:
```xml
<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://jetty.org/configure_10_0.dtd">
<Configure …
```
> Allow for customization of the Jetty WebAppContext

- alpine-executable-war/src/main/java/alpine/embedded/EmbeddedJettyServer.java
Due to a change in Jetty 12 and the Servlet API 6, it is no longer valid to pass URL-encoded values as path parameters. This is problematic for REST APIs such as Dependency-Track's, where this behavior causes endpoints to be unusable with certain parameters: https://github.com/DependencyTrack/dependency-track/issues/4238
Restore the legacy behavior of Jetty 9 for now. For the next major version bump of Alpine, this can be reversed to follow Servlet API 6 more strictly.
> Fix breaking change due to Jetty / Servlet API URI compliance enforcement

- alpine-server/src/main/java/alpine/server/upgrade/UpgradeMetaProcessor.java
Related to DependencyTrack/dependency-track#1987
This is an addition to #557, DependencyTrack still does not start with `ALPINE_DATABASE_PASSWORD_FILE`.
Unfortunately, I do not have a functional Java environment, so I could not test this patch.
> Fix use of `getPropertyOrFile` for database password

- alpine-server/src/main/java/alpine/server/mail/SendMail.java
Fixes `SendMail` performing hostname verification despite `trustCert` being enabled.
In older implementations of the Java Mail API, `mail.smtp.ssl.checkserveridentity` defaulted to `false`. With Eclipse Angus, it was changed to `true`.
https://github.com/eclipse-ee4j/angus-mail/pull/14
> Fix `SendMail` performing hostname verification despite `trustCert` being enabled

- .github/workflows/maven.yml
- .github/workflows/publish-snapshot.yml
- .github/workflows/release.yml
Download progress is not useful and just clutters the build logs.
Also fix CI workflow running twice for each PR commit.
> Disable Maven transfer progress logs in CI

- alpine-server/src/main/java/alpine/server/filters/AuthenticationFilter.java
Allows applications that make use of the MDC to better track which principal performed what API operation.
> Populate `principal` MDC variable in `AuthenticationFilter`

- alpine-server/src/main/java/alpine/server/filters/RequestMdcEnrichmentFilter.java
- alpine-server/src/test/java/alpine/server/filters/RequestMdcEnrichmentFilterTest.java
Logs emitted during request handling can be ambiguous if a resource class contains many methods.
Access control failure logs are harder to interpret without the additional context of which endpoint was attempted to be accessed.
This change enriches the logger's MDC with both the request method, and the request URI.
If an endpoint accepts path parameters, the `requestUri` MDC variable will only contain the respective placeholder, *not* the parameter values themselves. This keeps values constant, making it easier to filter through logs.
> Enrich MDC with request method and request URI

- alpine-common/src/main/java/alpine/Config.java
- alpine-server/src/main/java/alpine/server/AlpineServlet.java
- example/src/main/resources/application.properties
The implementation uses busy-looping which causes excessive CPU usage for no benefit at all.
Given we already have `/health` and `/metrics` endpoints to monitor applications, watchdog logging is not necessary anymore.
This was identified as an issue via https://github.com/DependencyTrack/dependency-track/issues/5021
> Remove watchdog logging

- alpine-common/pom.xml
- alpine-executable-war/pom.xml
- alpine-infra/pom.xml
- alpine-model/pom.xml
- alpine-server/pom.xml
- pom.xml
And add missing `name` properties to Maven modules. Central validates their presence now: https://central.sonatype.org/publish/requirements/#project-name-description-and-url
> Revert version to 3.3.0-SNAPSHOT

- alpine-common/pom.xml
- alpine-executable-war/pom.xml
- alpine-infra/pom.xml
- alpine-model/pom.xml
- alpine-server/pom.xml
Central validates their presence now: https://central.sonatype.org/publish/requirements/#project-name-description-and-url
> Add missing `name` properties to Maven modules
